package main

import (
	"math/rand"

	"gonum.org/v1/gonum/mat"
)

// InitializeEcosystem() takes:
// data from user input: numSpecies int; growthRate float64 – for grass, the only prey in the ecosystem; deathRate []float64 – for all other species.
// It initializes the ecosystem object with a certain number of species, and returns an Ecosystem object.
// interaction matrix and deathGrowth matrix are generated by two help functions.
func InitializeEcosystem(numSpecies int, interaction mat.Matrix, deathGrowth mat.Vector) *Ecosystem {
	// initialize an Ecosystem object and a species slice
	var ecosystem *Ecosystem
	species := make([]*Specie, numSpecies)

	// assign attributes values
	ecosystem.interaction = InitializeInteractionMatrix(species)
	ecosystem.deathGrowth = deathGrowth
	ecosystem.species = species

	// set the index for each specie, starting from 0
	index := 0

	// range through species slice in ecosystem, adding attributes to each specie
	// default set ecosystem.species[0] as grass – prey; all other species are predator
	for _, specie := range species {

		specie.population = 100 // we can reset this value
		specie.index = index
		ecosystem.species = append(ecosystem.species, specie)

		// increase index by one for each specie
		index++
	}

	return ecosystem
}

func InitializePop(species []*Specie) mat.Matrix {
	// get the length of the species slice
	numSpecies := len(species)

	// range through the species slice, and extract them all into a slice
	pop := make([]float64, numSpecies)
	for _, specie := range species {
		pop[specie.index] = specie.population
	}

	// convert the slice into a matrix
	popMatrix := mat.NewDense(numSpecies, 1, pop)

	return popMatrix
}

// InitializeInteractionMatrix() takes a species slice, and returns an interaction matrix.
// The interaction matrix is a square matrix with the size of the number of species.
// The diagonal elements are all 0, and the off-diagonal elements are randomly generated.
// The off-diagonal elements are the interaction coefficients between species.
// The interaction coefficients are randomly generated between -1 and 1.
func InitializeInteractionMatrix(species []*Specie) mat.Matrix {
	// get the length of the species slice
	numSpecies := len(species)

	// initialize a slice to store the interaction coefficients
	interaction := make([]float64, numSpecies*numSpecies)

	// range through the species slice, and assign random interaction coefficients to each specie. Make sure species[i][j] should be the same as species[j][i].
	for i := 0; i < numSpecies; i++ {
		for j := 0; j < numSpecies; j++ {
			if i == j {
				interaction[i*numSpecies+j] = 0
			} else {
				interaction[i*numSpecies+j] = rand.Float64()*2 - 1
				interaction[j*numSpecies+i] = interaction[i*numSpecies+j]
			}
		}
	}

	// convert the slice into a matrix
	interactionMatrix := mat.NewDense(numSpecies, numSpecies, interaction)

	return interactionMatrix
}
