package main

import (
	"gonum.org/v1/gonum/mat"
)

// InitializeEcosystem() takes:
// data from user input: numSpecies int; growthRate float64 – for grass, the only prey in the ecosystem; deathRate []float64 – for all other species.
// It initializes the ecosystem object with a certain number of species, and returns an Ecosystem object.
// interaction matrix and deathGrowth matrix are generated by two help functions.
func InitializeEcosystem(numSpecies int, interaction mat.Matrix, deathGrowth mat.Vector) *Ecosystem {
	// initialize an Ecosystem object and a species slice
	var ecosystem *Ecosystem
	species := make([]*Specie, numSpecies)

	// assign attributes values
	ecosystem.interaction = interaction
	ecosystem.deathGrowth = deathGrowth
	ecosystem.species = species

	// set the index for each specie, starting from 0
	index := 0

	// range through species slice in ecosystem, adding attributes to each specie
	// default set ecosystem.species[0] as grass – prey; all other species are predator
	for _, specie := range species {

		specie.population = 100 // we can reset this value
		specie.index = index
		ecosystem.species = append(ecosystem.species, specie)

		// increase index by one for each specie
		index++
	}

	return ecosystem
}

func InitializePop(species []*Specie) mat.Matrix {
	// get the length of the species slice
	numSpecies := len(species)

	// range through the species slice, and extract them all into a slice
	pop := make([]float64, numSpecies)
	for _, specie := range species {
		pop[specie.index] = specie.population
	}

	// convert the slice into a matrix
	popMatrix := mat.NewDense(numSpecies, 1, pop)

	return popMatrix
}

// ecosystem.interaction = IniInterMatrix()
// ecosystem.deathGrowth = IniRateMatrix()
